name: backend-helm
phoenix:
  image:
    repository: phoenix-backend2/4a5cd96ef072  # Remplacez par le nom souhaité pour votre image locale
    tag: latest
    id: 4a5cd96ef072
  environment:
    PGUSER: postgres
    PGPASSWORD: postgres
    PGDATABASE: time_manager_dev
    PGPORT: 5432
    PGHOST: db
  ports:
    - 4000:4000
nginx:
  image:
    repository: nginx
    tag: latest
  ports:
    - 8000:8000
db:
  image:  
    repository: postgres
    tag: latest
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: time_manager_dev
  ports:
    - 5432:5432
