apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.environment.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.environment.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.db.environment.POSTGRES_DB }}
