version: '3'

# Containers we're going to run.
services:
   # Our Phoenix container.
   phoenix:
      # The build parameters for this container.
      build:
         # Here we define that it should build from the current directory.
         context: .
      environment:
         # Variables to connect to our Postgres server.
         PGUSER: postgres
         PGPASSWORD: postgres
         PGDATABASE: time_manager_dev
         PGPORT: 5432
         # Hostname of our Postgres container.
         PGHOST: db
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - '4000:4000'
      networks:
          - postgres-network
      depends_on:
         # The DB container needs to be started before we start this container.
         - db
   nginx:
      image: nginx
      container_name: reverse-proxy
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf  # Montez le fichier de configuration Nginx.
      ports:
         - '8000:8000'  # Port du reverse proxy Nginx.
      networks:
         - postgres-network
   db:
      image: postgres
      container_name: phoenix-postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: time_manager_dev
      ports:
        - "5432:5432"
      networks:
          - postgres-network
      restart: always
      volumes:
         - pgdata:/var/lib/postgresql/data
# Define the volumes.
volumes:
   pgdata:

networks:
   postgres-network: